### ISSUE TITLE
Is there a way for this to work without the user having javascript enabled?

### ISSUE THREAD

**Issue by joemcl** [TechToThePeople/noverwrite#10]
This is not really an issue but a question and a request - is there a way for the functionality to work without the user having java script enabled, which is tough to require and frankly is not ideal. I have enabled the extension and like the idea. But I have users managing to overwrite their own records nonetheless. So Xavier - is there a way to do this without javascript, and/or on the server side only?

**Comment by tttp** [comment]
Hi,

Using a buildform hook could work... PR welcome ;)

Out of curiosity, is this something that happen on a regular basis with your constituents or is this one vocal but very close to your org one?

**Comment by joemcl** [comment]
Inevitably every new staff person user does this at least once, and I have to go back in and fix their record and the contributor's record. We have about 35 staff users.

**Comment by tttp** [comment]
and your staff doesn't have js enabled as a policy?

**Comment by joemcl** [comment]
No, our staff does not have javascript enabled as a policy.

**Comment by colemanw** [comment]
Weird policy
