### ISSUE TITLE
eu.tttp.noverwrite and civicrm 4.7.21

### ISSUE THREAD

**Issue by artd** [TechToThePeople/noverwrite#16]
Is this working together?
Any known issues?
We have a joomla! civicrm 4.7.21 system running with latest eu.tttp.noverwrite 1.3 and it doesn't seem to work.
regards
raphael

**Comment by kngs** [comment]
I have this problem too on multiple Joomla sites (works great on Drupal and WP!) Thanks -

**Comment by tttp** [comment]
does it display any error?

**Comment by artd** [comment]
Hi Xavier
no nothing
It is also not working with 4.7.23 bwt.
Best regards
R

**Comment by kngs** [comment]
I have also encountered a WP site running 4.7.29 where this use to work (at least I think so!) but is now not working on profiles (works for profiles embedded in contribution page after I reinstalled when alerted to the problem).  I get the following message when logged in and visit a profile page:

Notice: Undefined index: value in /home/cooldavis/www/www/wp-content/plugins/files/civicrm/extensions/eu.tttp.noverwrite/noverwrite.php on line 33

**Comment by tttp** [comment]
you can ignore the notice, but I'll try to find out what's the issue
