### ISSUE TITLE
&amp;cs= syntaxt prevents extension from working

### ISSUE THREAD

**Issue by magnolia61** [TechToThePeople/noverwrite#17]
Just discovered something interesting:

The links we mail our volunteers to register with a checksum link look like this:

`https://www.ourdomain.nl/civicrm/event/register?reset=1&amp;id=123&amp;cs=99ab996456400b1534646f9d7f33b120633f8100768_1515251415_1440&amp;cid=4567&amp;utm_source=mailwervingkk&amp;utm_medium=email&amp;utm_campaign=formbk1_prefilled`

But using this syntax does not invoke the readonly part where this extension is meant for.
Turns out I only need to change the &amp; to & for the checksum (cs).

`https://www.ourdomain.nl/civicrm/event/register?reset=1&amp;id=123&cs=99ab996456400b1534646f9d7f33b120633f8100768_1515251415_1440&amp;cid=4567&amp;utm_source=mailwervingkk&amp;utm_medium=email&amp;utm_campaign=formbk1_prefilled`

So probably with a small change of code this extension will work with both &amp; and & I guess. Just reporting because I would not have a clue where and what to change...

**Comment by joannechester** [comment]
@magnolia61   "Turns out I only need to change the & to & for the checksum (cs)" ??

**Comment by magnolia61** [comment]
;-) code is translated. I mean change "`&amp;`" into "&"

**Comment by tttp** [comment]
Hi,

I don't think it has something to do with the extension, it's just that the cs param isn't properly seen when the & isn't correctly there

You should check what adds the amp; in the html, I don't think the url should be html encoded
