### ISSUE TITLE
Update Civi version compatibility and release date

### ISSUE THREAD

**Issue by joemcl** [TechToThePeople/noverwrite#20]
Hi Xavier and thanks again for creating this. I'm installing this on 5.20.0 and testing it. Please update the compatible CiviCRM versions and version release date in info.xml and at https://civicrm.org/extensions/no-overwrite , if applicable.

**Comment by tttp** [comment]
We're finally bumping up the version and releasing. It only took a global pandemic. I'm not sure it was worth it, but hey ;)

**Comment by joemcl** [comment]
> We're finally bumping up the version and releasing. It only took a global pandemic. I'm not sure it was worth it, but hey ;)

Thanks!
