### ISSUE TITLE
Not working with checksums?

### ISSUE THREAD

**Issue by twomice** [TechToThePeople/noverwrite#21]
This extension appears not to do anything when viewing a profile as anonymous users with checksum (i.e., first name and last name are writable fields as if the extension were not installed).

- Civicrm version 5.21.1
- extension version 1.3
- First name and last name are correctly made read-only when viewing the profile as a lgged-in user.

Please let me know if you need any additional details.

**Comment by tttp** [comment]
Hi,

Thanks to the report, it should work indeed :(

I'll be on holiday for the next 3 weeks, so if you want to investigate,
please go ahead

**Comment by twomice** [comment]
Fixed in c4c257e43bb108b281d23f9f718a336a38c268b6.
