### ISSUE TITLE
Update screenshot on c.o listing

### ISSUE THREAD

**Issue by twomice** [TechToThePeople/noverwrite#24]
Hi @tttp The attached image was sent to me by @stoob as a proposed improvement for the screenshot on the c.o listing at https://civicrm.org/extensions/no-overwrite/. 

Are you agreeable to that?

![new_screenshot](https://user-images.githubusercontent.com/759449/114574792-2bfff700-9c3f-11eb-93a1-90ce640d3f2d.png)

**Comment by tttp** [comment]
I'd prefer a more neutral:
-first "Jane"
- last "Doe"
- org "ACME"
- email admin@example.org

(it took me a few sec to get the "Not CiviCRM Administrator", I thought it meant you need to be super admin to update)

... I know, I'm assuming that other users are as easily confused as I am, please indulge me, I'm not ready yet to face the truth ;)

**Comment by twomice** [comment]
Haha, yeah i see what you mean. @stoob do you want to try amending your screenshot?

**Comment by Stoob** [comment]
Fair point.  Here is a revised version.
![screenshot revised](https://user-images.githubusercontent.com/1683473/114585684-c446ad80-9c38-11eb-96a4-d8b4cd54c9c7.png)

**Comment by Stoob** [comment]
Fair point.  Here is a revised screenshot.  Thoughts?

![screenshot revised](https://user-images.githubusercontent.com/1683473/114585877-f1935b80-9c38-11eb-9a09-0d4a76bb5bd0.png)

**Comment by tttp** [comment]
Awesome!
Could you PR so credit where due or do you want one of us to do it?

**Comment by twomice** [comment]
I've now updated the image in the c.o listing. PR #25 also adds it to the readme and thus to the github repo main page.
