### ISSUE TITLE
create patch to update this version compaibility to 5.x+

### ISSUE THREAD

**Issue by Stoob** [TechToThePeople/noverwrite#26]
Already tested on multiple 5.x+ installs @twomice

**Comment by tttp** [comment]
++

**Comment by Stoob** [comment]
It looks like the code already lists 5.0 compatibility: https://github.com/TechToThePeople/noverwrite/blob/master/info.xml

But not the extensions page: https://civicrm.org/extensions/no-overwrite

Not sure why. Thoughts @tttp ?

**Comment by twomice** [comment]
Yeah, it's weird. Suspecting this might need help from the infrastructure side. Requested help here: https://lab.civicrm.org/infra/extdir/-/issues/6

**Comment by twomice** [comment]
@tttp The easiest solution seems to be issuing a new tag for "2.0"; actually I would prefer switching to 3-part version numbers, so this tag would be "2.0.0". But that also sends an incorrect message by implying a significant jump of some kind. 

Can you think of reasons not to do that, or prefer some other approach?

**Comment by twomice** [comment]
I'm gonna go ahead with the 2.0.0 version.

**Comment by twomice** [comment]
Fixed in  62d0512  and tag "v2.0.0" created. This tag should be picked up and released by civicrm.org within 24 hours. I'll leave this ticket open until that release appears.

**Comment by Stoob** [comment]
Hurray @twomice and @tttp it's in the civicrm.org page and also in the 'add new' tab of the Extensions page within a CiviCRM.  But there is a weird 'notes' link on the far right here: https://civicrm.org/extensions/no-overwrite

**Comment by tttp** [comment]
Glad it got updated! and we'll survive with the missing note ;)

**Comment by twomice** [comment]
@Stoob yeah that's a weird note link. Apparently it's auto-generated by the civicrm.org release script, and it's incorrect (it points to "https://github.com/TechToThePeople/noverwrite/-/releases/tag/2.0.0" but I believe the correct link would be "https://github.com/TechToThePeople/noverwrite/releases/tag/v2.0.0") We don't have a way to address this as extension authors, but I'll mention it to the c.o team.

**Comment by twomice** [comment]
FYI, issue created for incorrect Notes link: https://lab.civicrm.org/infra/extdir/-/issues/7
