### ISSUE TITLE
CiviCRM.org is showing outdated version on the extension page

### ISSUE THREAD

**Issue by wmortada** [TechToThePeople/noverwrite#27]
The latest version show on https://civicrm.org/extensions/no-overwrite is 1.24. It is not showing the more recent versions. Possibly this is because of the non-sequential numbering system (i.e. 1.24 sounds later than 1.5).

**Comment by twomice** [comment]
Duplicate of #26 , but yes I think @wmortada has the answer, of course. Thanks !

**Comment by wmortada** [comment]
Thanks! Apologies for the duplicate issue. I should have checked first.

**Comment by twomice** [comment]
No apology needed -- thanks for spotting the actual problem!
