### ISSUE TITLE
Upper Case

### ISSUE THREAD

**Issue by snapcase303** [TechToThePeople/noverwrite#7]
When i used this for event registration if the user uses lower case letters it changes the persons name to the lower case version - Example it changes Smith to smith. Anyone else having this issue?

**Comment by tttp** [comment]
Not sure I understand what is happening. is this when you save or on screen?

**Comment by snapcase303** [comment]
When a user registers for an event and they type in their name in lowercase
letters it saves their name as all lowercase letters. Just to be picky I
have everyone listed with their names capitalized. Any way to avoid this
from happening?



*From:* xavier dutoit [mailto:notifications@github.com]
*Sent:* Wednesday, March 4, 2015 12:20 PM
*To:* TechToThePeople/noverwrite
*Cc:* snapcase303
*Subject:* Re: [noverwrite] Upper Case (#7)



Not sure I understand what is happening. is this when you save or on screen?

—
Reply to this email directly or view it on GitHub
<https://github.com/TechToThePeople/noverwrite/issues/7#issuecomment-77202056>
.

**Comment by tttp** [comment]
So the goal is to transform SMITH or smith into Smith, I'm not sure what is the behaviour you want or what is happening on your tests, could you clarify what is typed, what is saved and what you expected?

**Comment by tttp** [comment]
stalled issue, closing.
